//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienLai
    {
        public int BienLaiID { get; set; }
        public Nullable<int> patientsID { get; set; }
        public string SoQuyenBienLai { get; set; }
        public Nullable<int> SoBienLai { get; set; }
        public byte LoaiBienLai { get; set; }
        public System.DateTime NgayBienLai { get; set; }
        public string LyDo { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public int employeesID_NguoiLap { get; set; }
        public Nullable<int> DepartmentsID_DieuTri { get; set; }
        public bool NgoaiGioHC { get; set; }
        public bool Huy { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
        public string employeesID_NguoiHuy { get; set; }
        public bool deleted { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
        public byte NumberUpdated { get; set; }
    }
}
