//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public int CalendarID { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public int employeesID { get; set; }
        public int DepartmentsID { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public string Description { get; set; }
        public bool isActivity { get; set; }
    }
}
