//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateBed
    {
        public int BedID { get; set; }
        public string BedCode { get; set; }
        public string BedName { get; set; }
        public Nullable<byte> PersonNumberMax { get; set; }
        public string Discription { get; set; }
        public int DepartmentsID { get; set; }
        public bool isActivity { get; set; }
    }
}
