//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuChiDinhDetail
    {
        public int DichVuChiDinhDetailsID { get; set; }
        public int DichVuChiDinhID { get; set; }
        public int DichVuID { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal ThanhTien { get; set; }
        public decimal TienBNCT { get; set; }
        public decimal TienBHCT { get; set; }
        public byte LoaiThanhToan { get; set; }
        public byte TyLeThanhToan { get; set; }
        public byte TrangThaiThanhToan { get; set; }
        public int BienLaiID { get; set; }
        public byte MienGiam { get; set; }
        public byte XaHoiHoa { get; set; }
        public string GhiChu { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual DichVuChiDinh DichVuChiDinh { get; set; }
        public virtual DMDichVu DMDichVu { get; set; }
    }
}
