//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuChiDinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVuChiDinh()
        {
            this.DichVuChiDinhDetails = new HashSet<DichVuChiDinhDetail>();
        }
    
        public int DichVuChiDinhID { get; set; }
        public int patientsID { get; set; }
        public int KhamBenhID { get; set; }
        public int DepartmentsID { get; set; }
        public int employeesID { get; set; }
        public Nullable<int> DepartmentsPerformID { get; set; }
        public Nullable<int> performerID { get; set; }
        public System.DateTime NgayChiDinh { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
        public Nullable<System.DateTime> NgayKetQua { get; set; }
        public string BarCode { get; set; }
        public bool emergency { get; set; }
        public int registrationNumber { get; set; }
        public string BenhPham { get; set; }
        public Nullable<System.DateTime> ThoiGianLayBenhPham { get; set; }
        public int SoTT { get; set; }
        public byte Status { get; set; }
        public bool deleted { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVuChiDinhDetail> DichVuChiDinhDetails { get; set; }
    }
}
