//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMBenhVien
    {
        public int BenhVienID { get; set; }
        public string MaBenhVien { get; set; }
        public string TenBenhVien { get; set; }
        public string MaBenhVienChuQuan { get; set; }
        public string DiaChi { get; set; }
        public int TuyenBV { get; set; }
        public int HangBV { get; set; }
        public string HinhThucBV { get; set; }
        public bool Connected { get; set; }
        public bool deleted { get; set; }
        public bool Status { get; set; }
        public int Cap { get; set; }
    }
}
