//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMChucVu
    {
        public int ChucVuID { get; set; }
        public string ChucVuCode { get; set; }
        public string ChucVuName { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
    }
}
