//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMDichVu
    {
    
        public int DichVuID { get; set; }
        public int NhomDichVuID { get; set; }
        public byte LoaiDichVu { get; set; }
        public string TenDichVu { get; set; }
        public string MaDichVu { get; set; }
        public string TenTheoBYT { get; set; }
        public string MaTheoBYT { get; set; }
        public int DanhMucID_DonVi { get; set; }
        public decimal GiaBHYT { get; set; }
        public decimal GiaVienPhi { get; set; }
        public Nullable<decimal> GiaBHYTGioiHanTT { get; set; }
        public Nullable<decimal> GiaPhuThu { get; set; }
        public string partientsObjectIDs { get; set; }
        public string DepartmentsIDs { get; set; }
        public bool deleted { get; set; }
        public bool Status { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
        public byte NumberUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVuChiDinhDetail> DichVuChiDinhDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMDichVuCLSang> DMDichVuCLSangs { get; set; }
    }
}
