//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMDuoc
    {
        public int DuocID { get; set; }
        public int NhomDichVuID { get; set; }
        public string TenDuoc { get; set; }
        public string MaDuoc { get; set; }
        public string TenHoatChat { get; set; }
        public string TenTheoBYT { get; set; }
        public string MaTheoBYT { get; set; }
        public string HamLuong { get; set; }
        public int DanhMucID_DonViN { get; set; }
        public int DanhMucID_DonViSD { get; set; }
        public int TyleQuyDoi { get; set; }
        public decimal GiaBHYT { get; set; }
        public decimal GiaVienPhi { get; set; }
        public Nullable<decimal> GiaBHYTGioiHanTT { get; set; }
        public string SoDangKy { get; set; }
        public Nullable<int> DanhMucID_DuongDung { get; set; }
        public string GoiThau { get; set; }
        public Nullable<int> NamThau { get; set; }
        public string NhomThau { get; set; }
        public string QuyetDinhSo { get; set; }
        public Nullable<System.DateTime> QuyetDinhNgay { get; set; }
        public Nullable<int> CompanyID_SX { get; set; }
        public Nullable<int> CompanyID_DK { get; set; }
        public string QuyCach { get; set; }
        public bool DongY { get; set; }
        public string DongY_NguonGoc { get; set; }
        public Nullable<byte> DongY_TyLeSP { get; set; }
        public Nullable<byte> DongY_TyLeBQ { get; set; }
        public Nullable<byte> DongY_TinhTrangNhap { get; set; }
        public Nullable<byte> DongY_YCSD { get; set; }
        public string DongY_BoPhanSD { get; set; }
        public Nullable<byte> DongY_PhuongPhap { get; set; }
        public string partientsObjectIDs { get; set; }
        public string DepartmentsIDs { get; set; }
        public bool deleted { get; set; }
        public bool Status { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
        public byte NumberUpdated { get; set; }
    }
}
