//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HenKham
    {
        public int HenKhamID { get; set; }
        public int patientsID { get; set; }
        public int KhamBenhID { get; set; }
        public string MaICDall { get; set; }
        public System.DateTime NgayHenKham { get; set; }
        public int DepartmentsID { get; set; }
    }
}
