//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MossHospitalEntities : DbContext
    {
        public MossHospitalEntities()
            : base("name=MossHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetsCate> AssetsCates { get; set; }
        public virtual DbSet<AssetsType> AssetsTypes { get; set; }
        public virtual DbSet<BienLai> BienLais { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<ChuyenVien> ChuyenViens { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DichVuChiDinh> DichVuChiDinhs { get; set; }
        public virtual DbSet<DichVuChiDinhDetail> DichVuChiDinhDetails { get; set; }
        public virtual DbSet<DMBenhVien> DMBenhViens { get; set; }
        public virtual DbSet<DMChucVu> DMChucVus { get; set; }
        public virtual DbSet<DmCompany> DmCompanies { get; set; }
        public virtual DbSet<DMDanhmuc> DMDanhmucs { get; set; }
        public virtual DbSet<DMDichVu> DMDichVus { get; set; }
        public virtual DbSet<DMDichVuCLSang> DMDichVuCLSangs { get; set; }
        public virtual DbSet<DMDuoc> DMDuocs { get; set; }
        public virtual DbSet<DMICD10> DMICD10 { get; set; }
        public virtual DbSet<DmKqClsMau> DmKqClsMaus { get; set; }
        public virtual DbSet<DMMucHuong> DMMucHuongs { get; set; }
        public virtual DbSet<DMNhomDichVu> DMNhomDichVus { get; set; }
        public virtual DbSet<DMQuanHuyen> DMQuanHuyens { get; set; }
        public virtual DbSet<DMTinhThanh> DMTinhThanhs { get; set; }
        public virtual DbSet<DMXaPhuong> DMXaPhuongs { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<GiaHistory> GiaHistories { get; set; }
        public virtual DbSet<HenKham> HenKhams { get; set; }
        public virtual DbSet<KBVaoVien> KBVaoViens { get; set; }
        public virtual DbSet<KhamBenh> KhamBenhs { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<NhapKho> NhapKhoes { get; set; }
        public virtual DbSet<NhapKhoDetail> NhapKhoDetails { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<patientsObject> patientsObjects { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<QuaTrinhDT> QuaTrinhDTs { get; set; }
        public virtual DbSet<RaVien> RaViens { get; set; }
        public virtual DbSet<StoreBalance> StoreBalances { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemConfig> SystemConfigs { get; set; }
        public virtual DbSet<ThuocChiDinh> ThuocChiDinhs { get; set; }
        public virtual DbSet<ThuocChiDinhDetail> ThuocChiDinhDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<XuatKho> XuatKhoes { get; set; }
        public virtual DbSet<XuatKhoDetail> XuatKhoDetails { get; set; }
        public virtual DbSet<CateBed> CateBeds { get; set; }
    }
}
