//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapKho
    {
        public int NhapKhoID { get; set; }
        public byte LoaiPhieuNhap { get; set; }
        public int DepartmentsID_KhoN { get; set; }
        public Nullable<int> DepartmentsID_KhoXT { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> XuatKhoID { get; set; }
        public Nullable<int> SoPhieuLinh { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public Nullable<System.DateTime> NgayCT { get; set; }
        public string SoCT { get; set; }
        public string NguoiGiao { get; set; }
        public string NoiDung { get; set; }
        public byte ThanhToan_status { get; set; }
        public Nullable<System.DateTime> ThanhToan_Date { get; set; }
        public byte Duyet_status { get; set; }
        public Nullable<int> Duyet_employeesID { get; set; }
        public Nullable<System.DateTime> Duyet_Date { get; set; }
        public bool deleted { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
        public byte NumberUpdated { get; set; }
    }
}
