//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhDT
    {
        public int KhamBenhChiTiet { get; set; }
        public int KhamBenhID { get; set; }
        public Nullable<int> PhongDT_ID { get; set; }
        public Nullable<int> GiuongDT_ID { get; set; }
        public System.DateTime NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
    }
}
