//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreBalance
    {
        public int StoreBalanceID { get; set; }
        public int DepartmentsID_KhoN { get; set; }
        public int DuocID { get; set; }
        public string SoLo { get; set; }
        public Nullable<System.DateTime> HanDung { get; set; }
        public decimal GiaNhap { get; set; }
        public decimal GiaVAT { get; set; }
        public decimal TongSoNhap { get; set; }
        public decimal TongSoXuat { get; set; }
    }
}
