//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public string MaBenhVien { get; set; }
        public Nullable<int> employeesID_ThuTruong { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string MaNganSach { get; set; }
        public string SoTaiKhoan { get; set; }
        public string MaTinh { get; set; }
        public Nullable<int> employeesID_KeToanTruong { get; set; }
        public Nullable<int> employeesID_TruongKhoaDuoc { get; set; }
        public string GiamDinhBHNoiTru { get; set; }
        public string GIamDinhBHNgoaiTru { get; set; }
        public string CoQuanChuQuan { get; set; }
        public string CoQuanBH { get; set; }
        public string CoQuanBHChuQuan { get; set; }
        public decimal GioiHanTTBHYT100 { get; set; }
        public Nullable<System.TimeSpan> TimeWorkAMFrom { get; set; }
        public Nullable<System.TimeSpan> TimeWorkAMTo { get; set; }
        public Nullable<System.TimeSpan> TimeWorkPMFrom { get; set; }
        public Nullable<System.TimeSpan> TimeWorkPMTo { get; set; }
        public string UrlLoGo { get; set; }
        public string Slogan { get; set; }
        public string StructpatientsCode { get; set; }
        public Nullable<int> RecordPape { get; set; }
    }
}
