//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatKhoDetail
    {
        public int XuatKhoDetailID { get; set; }
        public int XuatKhoID { get; set; }
        public int DuocID { get; set; }
        public decimal GiaVAT { get; set; }
        public decimal ThanhTienVAT { get; set; }
        public string SoLo { get; set; }
        public decimal GiaXuat { get; set; }
        public decimal ThanhTienXuat { get; set; }
        public byte TyLeGia { get; set; }
        public decimal SoLuong { get; set; }
        public int StoreBalanceID { get; set; }
        public bool deleted { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
        public byte NumberUpdated { get; set; }
    }
}
