//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AssetsCate
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AssetsCateID { get; set; }
        public int AssetsTypesID { get; set; }
        public string AssetsCode { get; set; }
        public string AssetsName { get; set; }
        public Nullable<int> SoNamSuDung { get; set; }
        public Nullable<int> TyLeHaoMon { get; set; }
        public Nullable<decimal> GiaQuyUoc { get; set; }
    }
}
