//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AssetsType
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AssetsTypesID { get; set; }
        public string TypesName { get; set; }
        public string TypesCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> AssetsTypesID_parents { get; set; }
        public Nullable<int> SoNamSuDung { get; set; }
        public Nullable<int> TyLeHaoMon { get; set; }
        public int TypesGroup { get; set; }
        public int levels { get; set; }
        public bool deleted { get; set; }
        public bool Status { get; set; }
    }
}
