//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ChuyenVien
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int patientsID { get; set; }
        public string MaBenhVien_CV { get; set; }
        public string TinhTrangCV { get; set; }
        public string LyDoCV { get; set; }
        public string HinhThucCV { get; set; }
        public Nullable<System.DateTime> HanCV { get; set; }
        public string ChanDoanCV { get; set; }
        public string NguoiChuyen { get; set; }
        public string KetQua { get; set; }
    }
}
