//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMDichVuCLSang
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int DichVuCLS_ID { get; set; }
        public int DichVuID { get; set; }
        public string TenDichVuCLS { get; set; }
        public int SoTT_Form { get; set; }
        public int SoTT_Report { get; set; }
        public string KetQuaMau { get; set; }
        public string TSBT_Nam { get; set; }
        public string TSBT_Nu { get; set; }
        public bool deleted { get; set; }
        public bool Status { get; set; }
    
        public virtual DMDichVu DMDichVu { get; set; }
    }
}
