//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMXaPhuong
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int XaPhuongID { get; set; }
        public string XaPhuong_Code { get; set; }
        public string XaPhuong_Name { get; set; }
        public int QuanHuyenID { get; set; }
        public string GoTat { get; set; }
        public bool XaPhuong_Status { get; set; }
        public byte XaPhuong_Cap { get; set; }
    }
}
