//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int employeesID { get; set; }
        public int DepartmentsID { get; set; }
        public string DepartmentsID_active { get; set; }
        public string employeesName { get; set; }
        public string employeesCode { get; set; }
        public byte gender { get; set; }
        public string MaCCHN { get; set; }
        public int BacHocID { get; set; }
        public int ChucVuID { get; set; }
        public string DiaChi { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
        public bool deleted { get; set; }
    }
}
