//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaHistory
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int GiaHistoryID { get; set; }
        public int DichVuID { get; set; }
        public int patientsObjectID { get; set; }
        public decimal GiaSD { get; set; }
        public System.DateTime NgayHieuLuc { get; set; }
        public Nullable<System.DateTime> NgayHetHieuLuc { get; set; }
        public bool Status { get; set; }
    }
}
