//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.KhamBenhs = new HashSet<KhamBenh>();
        }
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int patientsID { get; set; }
        public string patientsCode { get; set; }
        public string patientsName { get; set; }
        public byte gender { get; set; }
        public string dayOfBirth { get; set; }
        public string mothOfBirth { get; set; }
        public string yearOfBirth { get; set; }
        public string age { get; set; }
        public string address { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime registrationDate { get; set; }
        public byte partientsObjectID { get; set; }
        public string cardNumber { get; set; }
        public Nullable<System.DateTime> expirationDateFrom { get; set; }
        public Nullable<System.DateTime> expirationDateTo { get; set; }
        public bool emergency { get; set; }
        public byte prioritize { get; set; }
        public string MaBenhVien_DKKCB { get; set; }
        public string MaBenhVien_KCB { get; set; }
        public string MaBenhVien_GioiThieu { get; set; }
        public string ChanDoanNoiGT { get; set; }
        public Nullable<byte> BHTuyen { get; set; }
        public Nullable<byte> BHNoiNgoaiTinh { get; set; }
        public string BHMaKhuVuc { get; set; }
        public Nullable<System.DateTime> BHNgayHanMuc { get; set; }
        public Nullable<byte> BHMienCungCT { get; set; }
        public Nullable<byte> BHMucHuong { get; set; }
        public byte LoaiBenhAn { get; set; }
        public string TrieuChung { get; set; }
        public string CMThu_HChieu { get; set; }
        public int peopleID { get; set; }
        public int DepartmentsID_Khoa { get; set; }
        public int DepartmentsID_PhongBuong { get; set; }
        public byte patientsStatus { get; set; }
        public int registrationNumber { get; set; }
        public Nullable<int> TinhThanhID { get; set; }
        public Nullable<int> QuanHuyenID { get; set; }
        public Nullable<int> XaPhuongID { get; set; }
        public string SoNhaThoPho { get; set; }
        public string NguoiThan_Ten { get; set; }
        public string NguoiThan_SoDT { get; set; }
        public Nullable<int> QuocTichID { get; set; }
        public Nullable<int> NgheNgiepID { get; set; }
        public Nullable<decimal> CanNang { get; set; }
        public bool OutTime { get; set; }
        public string partientsPicture { get; set; }
        public bool deleted { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
        public byte NumberUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhamBenh> KhamBenhs { get; set; }
        public virtual patientsObject patientsObject { get; set; }
    }
}
