//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int PermissionsID { get; set; }
        public int userID { get; set; }
        public int FeatureID { get; set; }
        public bool Views { get; set; }
        public bool New { get; set; }
        public bool Edit { get; set; }
        public bool Deleted { get; set; }
        public bool Prints { get; set; }
        public bool Approved { get; set; }
    }
}
