//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaVien
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int patientsID { get; set; }
        public System.DateTime NgayRaVien { get; set; }
        public byte SoNgayDT { get; set; }
        public byte KetQuaDT { get; set; }
        public byte HinhThucRV { get; set; }
        public string SoRaVien { get; set; }
        public string SoLuuTru { get; set; }
        public string MaYTe { get; set; }
        public int DepartmentID_TK { get; set; }
        public string PhuongPhapDT { get; set; }
        public string TinhTrangRaVien { get; set; }
        public string DienBienLamSang { get; set; }
        public string KetQuaCanLamSang { get; set; }
        public string ChuyenKhoa_Code { get; set; }
        public string LoiDan { get; set; }
        public string GhiChu { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
        public byte NumberUpdated { get; set; }
    }
}
