//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuocChiDinh
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int ThuocChiDinhID { get; set; }
        public int KhamBenhID { get; set; }
        public int patientsID { get; set; }
        public int DepartmentsID { get; set; }
        public int employeesID { get; set; }
        public int DepartmentsID_TK { get; set; }
        public byte LoaiDon { get; set; }
        public System.DateTime NgayYLenh { get; set; }
        public System.DateTime NgayNhap { get; set; }
    }
}
