//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuocChiDinhDetail
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int ThuocChiDinhDetailsID { get; set; }
        public int ThuocChiDinhID { get; set; }
        public int DuocID { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal ThanhTien { get; set; }
        public decimal TienBNCT { get; set; }
        public decimal TienBHCT { get; set; }
        public byte LoaiThanhToan { get; set; }
        public byte TyLeThanhToan { get; set; }
        public byte TrangThaiThanhToan { get; set; }
        public int BienLaiID { get; set; }
        public byte MienGiam { get; set; }
        public byte XaHoiHoa { get; set; }
        public string GhiChu { get; set; }
        public int SoPhieuLinh { get; set; }
        public byte Status { get; set; }
        public bool deleted { get; set; }
        public int userIDCreated { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public int userIDUpdated { get; set; }
        public byte NumberUpdated { get; set; }
    }
}
