//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Hospital.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public int userID { get; set; }
        public int employeesID { get; set; }
        public string userName { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public bool Status { get; set; }
        public bool deleted { get; set; }
        public bool locked { get; set; }
        public byte errorNumber { get; set; }
        public string Note { get; set; }
        public byte userLevel { get; set; }
    }
}
